name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile*'
      - 'homeserver.yaml'
      - 'log.config' 
      - 'element-config.json'
      - '.github/workflows/build-images.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SYNAPSE_IMAGE_NAME: korjavin/matrix-self-hosted/synapse
  ELEMENT_IMAGE_NAME: korjavin/matrix-self-hosted/element

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Synapse
        id: synapse-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.SYNAPSE_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Extract metadata for Element  
        id: element-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ELEMENT_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Synapse image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.synapse-meta.outputs.tags }}
          labels: ${{ steps.synapse-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Element image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.element
          push: true
          tags: ${{ steps.element-meta.outputs.tags }}
          labels: ${{ steps.element-meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image Summary
        run: |
          echo "🚀 Docker images built and pushed successfully!"
          echo "📦 Synapse image: ${{ env.REGISTRY }}/${{ env.SYNAPSE_IMAGE_NAME }}:latest"
          echo "📦 Element image: ${{ env.REGISTRY }}/${{ env.ELEMENT_IMAGE_NAME }}:latest"
          echo "🔄 Images are ready for Portainer deployment!"
          
